# Generated by Django 4.2.2 on 2023-07-01 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('isbn', models.BigIntegerField(primary_key=True, serialize=False)),
                ('issued', models.DateTimeField(blank=True, null=True)),
                ('authors', models.TextField(blank=True, null=True)),
                ('publishers', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('average_rating', models.IntegerField(blank=True, null=True)),
                ('popularity', models.BigIntegerField(blank=True, null=True)),
                ('report_score', models.IntegerField(blank=True, null=True)),
                ('cover_url', models.TextField(blank=True, null=True)),
                ('topic', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Books',
                'ordering': ('-issued',),
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('kurs', models.TextField(db_column='Kurs')),
                ('o_i', models.CharField(blank=True, choices=[('o', 'Obavezan'), ('i', 'Izboran')], db_column='o/i', default='i', null=True)),
                ('er', models.BooleanField(blank=True, db_column='ER', null=True)),
                ('simingod', models.IntegerField(blank=True, db_column='SIMinGod', null=True)),
                ('irmingod', models.IntegerField(blank=True, db_column='IRMinGod', null=True)),
                ('osmingod', models.IntegerField(blank=True, db_column='OSMinGod', null=True)),
                ('otmingod', models.IntegerField(blank=True, db_column='OTMinGod', null=True)),
                ('ogmingod', models.IntegerField(blank=True, db_column='OGMinGod', null=True)),
                ('ofmingod', models.IntegerField(blank=True, db_column='OFMinGod', null=True)),
                ('oemingod', models.IntegerField(blank=True, db_column='OEMinGod', null=True)),
                ('topics', models.TextField(blank=True, db_column='Topics', null=True)),
            ],
            options={
                'db_table': 'Courses',
            },
        ),
    ]
